---

- hosts: all
  remote_user: vagrant
  become: yes
  tasks:
   # tasks file for nginx
    - name: install nginx
      yum: 
        name=nginx 
        state=installed

    - name: nginx start
      service: 
        name=nginx 
        state=started
